### 1. SIF 메인 데이터

In [1]:
import pandas as pd

In [2]:
file_path = "data/한국산업안전보건공단_산업재해 고위험요인(SIF) 아카이브_20260401.xlsx"

df_main = pd.read_excel(
    file_path,
    sheet_name="아카이브(제조업등)",
    header=2
)

df_main.info()

<class 'pandas.DataFrame'>
RangeIndex: 2573 entries, 0 to 2572
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    0 non-null      float64
 1   연번            2573 non-null   int64
 2   산재업종
(대분류)    2573 non-null   str
 3   산재업종
(중분류)    2573 non-null   str
 4   산재업종
(소분류)    2573 non-null   str
 5   재해개요          2573 non-null   str
 6   기인물           2573 non-null   str
 7   고위험작업·상황      2573 non-null   str
 8   재해유발요인        2573 non-null   str
 9   위험성 감소대책(예시)  2573 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 201.1 KB

In [3]:
excel_file = pd.ExcelFile(file_path)

excel_file.sheet_names

['개요', '아카이브(제조업등)', '아카이브(건설업)']

In [4]:
df_main['산재업종\n(중분류)'].unique()

<StringArray>
[         '화학및고무제품제조업',           '출판·인쇄·제본업', '전기기계기구·정밀기구·전자제품제조업',
  '의약품·화장품·연탄·석유제품제조업',              '식료품제조업',         '수제품및기타제품제조업',
          '섬유및섬유제품제조업',            '선박건조및수리업',          '목재및종이제품제조업',
  '기계기구·금속·비금속광물제품제조업',               '금속제련업',          '전기가스증기수도사업',
                  '임업',                 '통신업',   '철도·항공·창고·운수관련서비스업',
            '육상및수상운수업',                  '어업',                  '농업',
                '농  업',               '해외파견자',                '주한미군',
   '전문·보건·교육·여가관련서비스업',       '시설관리및사업지원서비스업',            '부동산업및임대업',
          '도소매·음식·숙박업',             '기타의각종사업',        '국가및지방자치단체의사업',
              '금융및보험업',   '석회석·금속·비금속광업및기타광업',            '석탄광업및채석업']
Length: 30, dtype: str

In [5]:
mask = (df_main['산재업종\n(중분류)'] == '전문·보건·교육·여가관련서비스업')
df_main[mask]['산재업종\n(소분류)'].unique()

<StringArray>
[   '정보처리및기타컴퓨터운용관련사업',        '오락·문화및운동관련사업',             '연구및개발사업',
           '보건및사회복지사업',          '기타과학기술서비스업',          '그외기타기술서비스업',
              '교육서비스업',                 '광고업',          '골프장및경마장운영업',
           '경영컨설팅서비스업', '건축기술,엔지니어링및관련기술서비스업']
Length: 11, dtype: str

In [6]:
df_main['기인물'].unique()

<StringArray>
[          '분류 불가',            '컨베이어',             '혼합기',    '지붕·대들보(슬레이트)',
         '중량물(톤백)',      '지붕·대들보(천막)',        '화학물질(황산)',        '건설기계(로더)',
             '지게차',     '줄걸이기구(톤백 끈)',
 ...
         '독충(진드기)',      '기타 설비(양수기)',       '기타 설비(국솥)',         '재활용수거차량',
     '기타 설비(턴테이블)',           '암석/암반', '기타 설비(파쇄기/텐선로드)',     '생산설비(석재절단기)',
          '마모된 나사',       '건설기계(천공기)']
Length: 626, dtype: str

In [7]:
df_main['재해유발요인'].unique()

<StringArray>
[                                      '『화물용 승강기 또는 리프트(기계식 주차설비 포함)의 운반구(기)에서 작업 또는 이동』하다가 승강로 내부 구조물과 운반구 사이에 끼임 또는 그 사이 개구부로 떨어짐 위험',
                                                                         '『설비에 안전장치가 설치되어 있지 않거나, 불량하거나, 설치된 안전장치를 해제한 상태』로 사용 중 사고 위험',
                                                               '『정비·보수·청소·교체·조정·점검 등의 작업 중 작업자 외 다른 사람이 설비를 가동』하여 갑자기 작동된 설비로 인한 사고 위험',
                                                                                         '『밟고 있던 구조물(또는 자재) 등의 파손·탈락 등』으로 넘어지거나 떨어짐 위험',
                                                   '『무게 또는 형태가 한쪽으로 치우치거나 무게중심이 높은(전도되기 쉬운) 물체 또는 적재상태가 불량한 물체 등』이 무너짐·전도·낙하로 인한 사고 위험',
                                                                                '『취급하는 물질이 배관·호스·용기 등에서 누출』로 인한 화학물질 접촉·질식 또는 화재·폭발 위험',
                                  '『차량(하역운반기계 또는 건설기계 포함)작업구역에서 출입통제 미실시』로 근로자(차량포함)가 작업차량 또는 운반하는 화물에 부딪히거나 깔림 또는 주변 구조물과 그 사이에 끼임 위험',
                                  '『근로자와 작업차량(하역운반기계 또는 건설기계 포함) 간 이동동선(통행로)를 구분하지 않은 상태』에서 근로자가 작업차량에 부딪히거나 깔림 또는 주변 구조물과 차량사이에 끼임 위험',
                                                                     '『줄걸이 기구의 용접 불량, 마모, 변형, 손상, 파단』으로 인해 운반하는 화물의 낙하·전도·비래 등으로 인한 위험',
 '근로자와 작업차량 간 『혼재작업 장소에서 근로자 이동과 작업차량(하역운반기계 또는 건설기계 포함) 운행을 통제하지 않은 상태』에서 근로자(차량 포함)가 작업차량에 부딪히거나 깔림 또는 주변 구조물과 작업차량 사이에 끼임 등으로 인한 위험',
 ...
                                                                                                   '『청소차량 후미 발판 등에 탑승하여 이동』으로 인한 사고 위험',
                                                                                                 '기타 분류(도로에서 작업 시 외부 차량의 충돌로 인한 사고 위험)',
                                                                                                          '기타 분류(차량에서 하차 중 주변 구조물에 찔림)',
                                                                                                 '기타 분류(소화약제 방출 시 저장용기 미고정으로 인한 사고 위험)',
                                                                                                           '기타 분류(중량물에 의한 컨베이어 역주행 위험)',
                                                                                          '『음료병에 들어있는 무향, 무채색의 화학물질』 을 음료수로 오인하여 음용 위험',
                                                                                                       '『본인 또는 타인의 교통법규 위반』으로 인한 사고 위험',
                                                                                   '『과속, 도로의 노면상태(빗길, 결빙, 포트홀 등)』 로 인한 차량, 건설기계 등 사고위험',
                                                                                                                        '기타 분류(운전미숙 등)',
                                                                                                          '기타 분류(화재로 비산된 불꽃에 의한 화재 위험)']
Length: 124, dtype: str

### 2. 산업중분류별 규모별 사고재해자수

In [8]:
df_2 = pd.read_csv("data/한국산업안전보건공단_산업중분류별 규모별 사고재해자수_20251231.csv")
df_2

,대업종,구분,5인 미만 근로자수,5인 - 9인 근로자수,10인 - 19인 근로자수,20인 - 29인 근로자수,30인 - 49인 근로자수,50인 - 99인 근로자수,100인 - 299인 근로자수,300인 - 499인 근로자수,500인 - 999인 근로자수,1000인 이상 근로자수
0,금융및보험업,금융및보험업,62,53,80,54,88,78,48,14,18,96
1,광 업,석탄광업및채석업,2,0,4,2,1,1,0,0,3,1
2,광 업,석회석·금속·비금속광업및기타광업,26,11,18,20,15,4,5,0,0,0
3,제조업,식료품제조업,444,406,610,301,399,418,425,110,59,27
4,제조업,섬유및섬유제품제조업,194,120,126,81,79,67,53,11,7,0
5,제조업,목재및종이제품제조업,368,226,235,115,89,68,103,23,3,0
6,제조업,출판·인쇄·제본업,80,56,72,49,28,44,17,6,1,0
7,제조업,화학및고무제품제조업,393,345,392,239,229,229,268,62,40,213
8,제조업,의약품·화장품·연탄·석유제품제조업,27,19,31,27,23,65,104,26,27,21
9,제조업,기계기구·금속·비금속광물제품제조업,2636,1553,1696,970,900,712,848,273,244,847
10,제조업,금속제련업,0,1,4,2,6,4,20,5,20,91
11,제조업,전기기계기구·정밀기구·전자제품제조업,208,155,179,112,126,194,250,150,79,195
12,제조업,선박건조및수리업,240,139,117,70,67,135,148,12,39,665
13,제조업,수제품및기타제품제조업,282,175,186,120,116,83,27,6,5,0
14,전기·가스·증기·수도사업,전기·가스·증기·수도사업,7,7,7,10,14,17,12,4,3,9
15,건설업,건설업,8277,2280,2812,1421,1156,1314,2266,983,543,472
16,운수·창고·통신업,철도·항공·창고·운수관련서비스업,1108,206,254,172,211,258,403,194,274,801
17,운수·창고·통신업,육상및수상운수업,6592,328,423,260,320,519,691,220,101,2989
18,운수·창고·통신업,통신업,29,22,20,31,27,44,5,1,2,0
19,임 업,임업,441,204,135,39,24,6,2,0,0,0
20,어 업,어업,16,15,6,0,0,0,0,0,0,0
21,농 업,농업,346,140,105,59,44,13,4,0,0,0
22,기타의사업,시설관리및사업지원서비스업,2645,2152,1869,907,1012,893,499,92,59,43
23,기타의사업,기타의각종사업,766,256,217,91,84,82,75,20,17,35
24,기타의사업,해외파견자,3,4,2,0,4,4,2,0,1,1
25,기타의사업,전문·보건·교육·여가관련서비스업,1837,992,1423,1032,1659,2196,1810,414,285,319
26,기타의사업,도소매·음식·숙박업,8406,3722,3074,1316,1151,755,759,402,217,206
27,기타의사업,부동산업및임대업,138,38,31,15,6,11,5,6,8,1
28,기타의사업,국가및지방자치단체의사업,461,340,707,896,1054,506,504,241,498,159
29,기타의사업,주한미군,0,1,2,0,2,1,12,2,1,15

In [9]:
df_2['구분'].unique()

<StringArray>
[             '금융및보험업',            '석탄광업및채석업',   '석회석·금속·비금속광업및기타광업',
              '식료품제조업',          '섬유및섬유제품제조업',          '목재및종이제품제조업',
           '출판·인쇄·제본업',          '화학및고무제품제조업',  '의약품·화장품·연탄·석유제품제조업',
  '기계기구·금속·비금속광물제품제조업',               '금속제련업', '전기기계기구·정밀기구·전자제품제조업',
            '선박건조및수리업',         '수제품및기타제품제조업',       '전기·가스·증기·수도사업',
                 '건설업',   '철도·항공·창고·운수관련서비스업',            '육상및수상운수업',
                 '통신업',                  '임업',                  '어업',
                  '농업',       '시설관리및사업지원서비스업',             '기타의각종사업',
               '해외파견자',   '전문·보건·교육·여가관련서비스업',          '도소매·음식·숙박업',
            '부동산업및임대업',        '국가및지방자치단체의사업',                '주한미군']
Length: 30, dtype: str

### 3. 산업중분류별 규모별 사고사망자수

In [10]:
df_3 = pd.read_csv("data/한국산업안전보건공단_산업중분류별 규모별 사고사망자수_20251231.csv")
df_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   대업종               30 non-null     str
 1   구분                30 non-null     str
 2   5인 미만 근로자수        30 non-null     int64
 3   5인 - 9인 근로자수      30 non-null     int64
 4   10인 - 19인 근로자수    30 non-null     int64
 5   20인 - 29인 근로자수    30 non-null     int64
 6   30인 - 49인 근로자수    30 non-null     int64
 7   50인 - 99인 근로자수    30 non-null     int64
 8   100인 - 299인 근로자수  30 non-null     int64
 9   300인 - 499인 근로자수  30 non-null     int64
 10  500인 - 999인 근로자수  30 non-null     int64
 11  1000인 이상 근로자수     30 non-null     int64
dtypes: int64(10), str(2)
memory usage: 2.9 KB

In [11]:
df_3['구분'].unique()

<StringArray>
[             '금융및보험업',            '석탄광업및채석업',   '석회석·금속·비금속광업및기타광업',
              '식료품제조업',          '섬유및섬유제품제조업',          '목재및종이제품제조업',
           '출판·인쇄·제본업',          '화학및고무제품제조업',  '의약품·화장품·연탄·석유제품제조업',
  '기계기구·금속·비금속광물제품제조업',               '금속제련업', '전기기계기구·정밀기구·전자제품제조업',
            '선박건조및수리업',         '수제품및기타제품제조업',       '전기·가스·증기·수도사업',
                 '건설업',   '철도·항공·창고·운수관련서비스업',            '육상및수상운수업',
                 '통신업',                  '임업',                  '어업',
                  '농업',       '시설관리및사업지원서비스업',             '기타의각종사업',
               '해외파견자',   '전문·보건·교육·여가관련서비스업',          '도소매·음식·숙박업',
            '부동산업및임대업',        '국가및지방자치단체의사업',                '주한미군']
Length: 30, dtype: str

In [17]:
df_3

,대업종,구분,5인 미만 근로자수,5인 - 9인 근로자수,10인 - 19인 근로자수,20인 - 29인 근로자수,30인 - 49인 근로자수,50인 - 99인 근로자수,100인 - 299인 근로자수,300인 - 499인 근로자수,500인 - 999인 근로자수,1000인 이상 근로자수
0,금융및보험업,금융및보험업,0,0,0,0,0,0,0,0,0,0
1,광 업,석탄광업및채석업,0,0,1,0,0,0,0,0,1,0
2,광 업,석회석·금속·비금속광업및기타광업,0,1,0,1,1,1,0,0,0,0
3,제조업,식료품제조업,5,2,1,0,2,1,0,0,0,1
4,제조업,섬유및섬유제품제조업,2,2,3,1,0,0,0,0,0,0
5,제조업,목재및종이제품제조업,2,1,0,1,1,0,3,0,0,0
6,제조업,출판·인쇄·제본업,2,0,0,0,0,0,0,0,0,0
7,제조업,화학및고무제품제조업,4,1,9,1,2,3,1,0,0,0
8,제조업,의약품·화장품·연탄·석유제품제조업,0,0,0,0,0,0,0,0,0,0
9,제조업,기계기구·금속·비금속광물제품제조업,23,8,16,9,11,8,10,2,1,2
10,제조업,금속제련업,0,0,0,0,0,0,0,0,0,1
11,제조업,전기기계기구·정밀기구·전자제품제조업,0,2,1,0,1,0,1,0,0,1
12,제조업,선박건조및수리업,4,0,1,2,0,0,1,0,0,2
13,제조업,수제품및기타제품제조업,3,0,2,0,0,1,0,0,0,0
14,전기·가스·증기·수도사업,전기·가스·증기·수도사업,0,0,0,0,0,2,0,0,0,0
15,건설업,건설업,153,45,48,15,24,10,46,7,6,7
16,운수·창고·통신업,철도·항공·창고·운수관련서비스업,10,4,3,1,7,2,2,0,5,1
17,운수·창고·통신업,육상및수상운수업,78,7,9,7,4,9,6,2,3,16
18,운수·창고·통신업,통신업,0,0,0,0,0,0,0,0,0,0
19,임 업,임업,13,5,0,0,0,0,0,0,0,0
20,어 업,어업,0,0,0,0,0,0,0,0,0,0
21,농 업,농업,4,1,0,0,0,0,0,0,0,0
22,기타의사업,시설관리및사업지원서비스업,24,14,11,6,5,3,1,0,0,0
23,기타의사업,기타의각종사업,3,1,0,1,0,0,0,0,0,1
24,기타의사업,해외파견자,0,1,0,0,0,0,0,0,0,0
25,기타의사업,전문·보건·교육·여가관련서비스업,5,2,7,3,2,6,2,1,0,2
26,기타의사업,도소매·음식·숙박업,18,8,1,0,0,0,1,0,0,0
27,기타의사업,부동산업및임대업,0,0,0,0,0,0,0,0,0,0
28,기타의사업,국가및지방자치단체의사업,1,2,0,1,3,1,0,0,3,0
29,기타의사업,주한미군,0,0,0,0,0,0,0,0,0,0

### 4. 산업중분류별 규모별 사업장수

In [12]:
df_4 = pd.read_csv("data/한국산업안전보건공단_산업중분류별 규모별 사업장수_20251231.csv")
df_4.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   대업종               30 non-null     str
 1   구분                30 non-null     str
 2   5인 미만 사업장수        30 non-null     int64
 3   5인 - 9인 사업장수      30 non-null     int64
 4   10인 - 19인 사업장수    30 non-null     int64
 5   20인 - 29인 사업장수    30 non-null     int64
 6   30인 - 49인 사업장수    30 non-null     int64
 7   50인 - 99인 사업장수    30 non-null     int64
 8   100인 - 299인 사업장수  30 non-null     int64
 9   300인 - 499인 사업장수  30 non-null     int64
 10  500인 - 999인 사업장수  30 non-null     int64
 11  1000인 이상사업장수      30 non-null     int64
dtypes: int64(10), str(2)
memory usage: 2.9 KB

In [13]:
df_4

,대업종,구분,5인 미만 사업장수,5인 - 9인 사업장수,10인 - 19인 사업장수,20인 - 29인 사업장수,30인 - 49인 사업장수,50인 - 99인 사업장수,100인 - 299인 사업장수,300인 - 499인 사업장수,500인 - 999인 사업장수,1000인 이상사업장수
0,금융및보험업,금융및보험업,16174,9125,10682,4230,3241,1563,688,110,74,65
1,광 업,석탄광업및채석업,19,7,3,2,3,1,2,0,1,0
2,광 업,석회석·금속·비금속광업및기타광업,605,129,139,57,34,8,3,0,0,0
3,제조업,식료품제조업,20837,5242,4095,1413,1209,799,392,45,16,7
4,제조업,섬유및섬유제품제조업,19040,3342,1875,678,487,254,87,8,3,0
5,제조업,목재및종이제품제조업,13172,2758,1698,559,328,147,93,9,1,0
6,제조업,출판·인쇄·제본업,14194,2207,1139,420,295,170,75,6,2,3
7,제조업,화학및고무제품제조업,25465,6588,4540,1883,1476,859,471,51,23,16
8,제조업,의약품·화장품·연탄·석유제품제조업,2037,582,451,257,243,265,220,34,18,7
9,제조업,기계기구·금속·비금속광물제품제조업,127675,26739,16837,6382,4487,2532,1201,141,75,41
10,제조업,금속제련업,93,40,35,15,22,19,34,4,4,6
11,제조업,전기기계기구·정밀기구·전자제품제조업,36890,8042,5123,2086,1731,1301,807,135,65,61
12,제조업,선박건조및수리업,4678,1473,1117,330,301,405,202,7,3,6
13,제조업,수제품및기타제품제조업,18153,3227,1975,727,435,190,47,2,1,0
14,전기·가스·증기·수도사업,전기·가스·증기·수도사업,2673,318,163,124,199,249,126,21,6,7
15,건설업,건설업,367601,30757,18996,5805,3908,2705,2361,603,274,81
16,운수·창고·통신업,철도·항공·창고·운수관련서비스업,36622,5693,3947,1535,1230,952,521,82,61,42
17,운수·창고·통신업,육상및수상운수업,53727,5033,4174,1625,1522,1213,719,75,36,18
18,운수·창고·통신업,통신업,3654,638,501,295,227,246,109,22,12,5
19,임 업,임업,9594,7809,3306,729,445,74,78,16,3,0
20,어 업,어업,1831,334,59,1,1,1,0,0,0,0
21,농 업,농업,29173,4374,1399,343,246,69,23,2,1,0
22,기타의사업,시설관리및사업지원서비스업,184120,56834,31006,9447,7003,4338,1880,213,124,33
23,기타의사업,기타의각종사업,167267,20690,7852,1904,1269,883,565,108,75,63
24,기타의사업,해외파견자,3722,598,424,173,149,142,75,9,11,1
25,기타의사업,전문·보건·교육·여가관련서비스업,345993,76874,46744,16216,13692,9965,4641,702,417,223
26,기타의사업,도소매·음식·숙박업,804274,112682,44752,10986,7027,3084,1553,186,106,49
27,기타의사업,부동산업및임대업,62708,3219,1050,258,136,73,51,14,7,2
28,기타의사업,국가및지방자치단체의사업,22550,8873,8830,5220,3658,1148,619,114,111,35
29,기타의사업,주한미군,35,18,30,7,15,33,26,5,2,6

### 5. 산업중분류별 규모별 사망만인율

In [14]:
df_5 = pd.read_csv("data/한국산업안전보건공단_산업중분류별 규모별 사망만인율_20251231.csv")
df_5.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   대업종        30 non-null     str
 1   구분         30 non-null     str
 2   5인 미만      30 non-null     float64
 3   5인-9인      30 non-null     float64
 4   10인-19인    30 non-null     float64
 5   20인-29인    30 non-null     float64
 6   30인-49인    30 non-null     float64
 7   50인-99인    30 non-null     float64
 8   100인-299인  29 non-null     float64
 9   300인-499인  27 non-null     float64
 10  500인-999인  28 non-null     float64
 11  1000인 이상   22 non-null     float64
dtypes: float64(10), str(2)
memory usage: 2.9 KB

In [15]:
df_5

,대업종,구분,5인 미만,5인-9인,10인-19인,20인-29인,30인-49인,50인-99인,100인-299인,300인-499인,500인-999인,1000인 이상
0,금융및보험업,금융및보험업,1.77,0.63,0.28,0.30,0.00,0.10,0.10,0.23,0.00,0.17
1,광 업,석탄광업및채석업,4444.44,2272.73,2045.45,2156.86,1724.14,8333.33,2258.06,NaN,1642.44,NaN
2,광 업,석회석·금속·비금속광업및기타광업,95.60,47.23,10.27,14.74,15.41,110.91,80.21,NaN,NaN,NaN
3,제조업,식료품제조업,2.22,0.58,0.36,0.30,0.65,0.18,0.48,0.00,0.00,2.28
4,제조업,섬유및섬유제품제조업,1.90,1.38,1.57,1.87,0.54,0.00,0.77,0.00,0.00,NaN
5,제조업,목재및종이제품제조업,0.89,1.65,1.76,0.75,1.62,1.00,2.77,0.00,0.00,NaN
6,제조업,출판·인쇄·제본업,0.86,0.00,0.00,0.00,0.91,0.00,0.88,0.00,0.00,0.00
7,제조업,화학및고무제품제조업,1.55,0.23,2.09,1.34,0.90,0.69,0.68,1.03,0.00,1.62
8,제조업,의약품·화장품·연탄·석유제품제조업,8.56,10.43,1.62,0.00,0.00,0.00,0.28,0.00,0.00,0.00
9,제조업,기계기구·금속·비금속광물제품제조업,3.73,2.16,1.80,2.03,2.01,1.73,1.25,1.71,0.40,0.74
10,제조업,금속제련업,0.00,0.00,0.00,0.00,0.00,6.83,7.55,0.00,3.76,0.75
11,제조업,전기기계기구·정밀기구·전자제품제조업,0.94,0.38,0.29,0.00,0.30,0.11,0.31,0.57,0.22,0.24
12,제조업,선박건조및수리업,15.50,2.02,1.41,7.73,4.42,2.01,1.43,0.00,0.00,6.70
13,제조업,수제품및기타제품제조업,2.36,0.00,1.50,0.58,0.00,0.78,2.65,0.00,0.00,NaN
14,전기·가스·증기·수도사업,전기·가스·증기·수도사업,0.00,0.00,0.00,0.00,1.30,1.15,0.46,0.00,0.00,0.00
15,건설업,건설업,4.76,3.66,3.10,2.03,2.32,1.28,1.86,0.61,0.89,0.78
16,운수·창고·통신업,철도·항공·창고·운수관련서비스업,2.36,1.08,0.75,0.83,2.16,0.61,0.48,0.00,1.63,0.50
17,운수·창고·통신업,육상및수상운수업,19.97,2.97,2.11,3.63,1.89,2.52,1.56,1.76,1.70,0.42
18,운수·창고·통신업,통신업,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.45,0.00
19,임 업,임업,6.02,1.62,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN
20,어 업,어업,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
21,농 업,농업,0.94,0.71,1.12,1.25,0.00,0.00,0.00,0.00,0.00,NaN
22,기타의사업,시설관리및사업지원서비스업,1.48,1.08,0.79,0.76,0.38,0.31,0.14,0.13,0.12,0.15
23,기타의사업,기타의각종사업,0.70,0.38,0.29,0.45,0.42,0.16,0.11,0.24,0.19,0.06
24,기타의사업,해외파견자,0.00,5.09,0.00,0.00,0.00,1.00,0.87,0.00,0.00,0.00
25,기타의사업,전문·보건·교육·여가관련서비스업,0.25,0.14,0.27,0.18,0.21,0.22,0.16,0.08,0.00,0.19
26,기타의사업,도소매·음식·숙박업,0.33,0.35,0.17,0.04,0.15,0.10,0.08,0.14,0.14,0.10
27,기타의사업,부동산업및임대업,0.12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
28,기타의사업,국가및지방자치단체의사업,0.72,0.34,0.16,0.32,0.38,0.13,0.21,0.23,0.51,0.00
29,기타의사업,주한미군,0.00,0.00,0.00,0.00,0.00,0.00,2.15,0.00,0.00,0.00